import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/app/components/ui/toaster";
import { ThemeProvider } from "@/app/components/theme-provider";
import { CursorProvider } from "@/app/components/cursor-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SanityHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider 
          attribute="class" 
          defaultTheme="system" 
          enableSystem={true}
          disableTransitionOnChange
          storageKey="sanity-hub-theme"
          themes={["light", "dark", "pure-dark"]}
        >
          <CursorProvider>
            {children}
          </CursorProvider>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
